apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    releaseTag: 4.20.13-multi
    visible: 'false'
  name: img4.20.13-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:efbea5c66fbec8713159d5e984756ab859c394fd1699438a903c342bbbe23ed2
