apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    releaseTag: 4.20.29-multi
    visible: 'true'
  name: img4.20.29-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:714d39574f46fd974fee192a01af54298f8b1079cf108ccbe56304586a20b45b
