apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    releaseTag: 4.21.8-multi
    visible: 'false'
  name: img4.21.8-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:279726490cdd8b98bcdf15fa4351a6021389cca096aacc5fe585fab02d893328
