---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.31-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.31-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:aea3624423e54d7ca2224823501e0c6d23f4f5f2ff2b335597d1ceb88b4bc2b2
