apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    releaseTag: 4.21.1-multi
    visible: 'false'
  name: img4.21.1-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:011b1362aff9e82a3b7ca720456618eaebcaf4582fda007ee9c5271d6716ef65
