apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    releaseTag: 4.21.16-multi
    visible: 'false'
  name: img4.21.16-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:49298645e9624e973e2e6592e4c98734f795c89f3f3ff538d6492e16a44c2135
