---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.37-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.37-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:e376df16156e36ea97c076e0ca69a173642f974976bcf2e2779f7476dd3b8135
