---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.23-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.23-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:d94ccd33d86600dfaf865425f5a92f33278a46d353e7b47c036c209c7bd47e09
