apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    releaseTag: 4.21.20-multi
    visible: 'false'
  name: img4.21.20-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:07ce1cd675277a87ab41af5d6447a6234db7647b1ce45eddf85d97a0de0545aa
