---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.34-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.34-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:b6bdbb9508197e3ca704994cfae3441d1ad3526a6569793919b8e3938dfc559a
