---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.19-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.19-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:ad0dcd979545ce4023293f4451a943ff8475949dc83b188f56e2d94b5cbfabfb
