---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.23-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.23-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:c58d65eeaf399b6850e5cc637a199ed44066819ccbc25877a6afd44ff861d841
