---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.0-ec.3-multi-appsub
  labels:
    channel: candidate
    visible: "false"
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.21.0-ec.3-multi@sha256:809d7a5c17ca6b8f2602ecf443bbe4bcc29b37645c8aafd3cd27f2b55f378909
