---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.21.0-ec.1-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.21.0-ec.1-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:db8ee32fa253e1dcd5977a9c75d426f251139b5372f960688e6bdbcf9da8ded7
