apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'true'
  name: img4.18.8-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.18.8-multi
