---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.0-ec.2-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.0-ec.2-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:fc88d0bf145c81989a4116bbb0e3d2724d9ab937efb7d217a10e7d7ff3031c50
