---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.18-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.18-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:4ebbe67679969175b6be1626a64eeab44191117abba298e43742d72b26bf2ecd
