---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.0-rc.2-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.0-rc.2-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:fec5d527b523894377f506cd12842f27a2503700007ccf03c10d2ca3e4cb7111
