---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.0-rc.1-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.0-rc.1-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:fec229030a05347654b43e6ca49efa1e168e3d13e217dc2b68818b3d01f3ec08
