---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.7-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.7-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:1a50a7c21acc0b113aa74c187bec8798cb58481c065a4c5a0e25df6bc46b8815
