---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.8-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.8-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:92d693f64e1031405664de1593ea81e334dacda03cd2643c9fea474ccf35d51c
