---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.22.0-ec.2-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.22.0-ec.2-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:f4261c7032baed992e9340451eac5e2139a0b76dc7b1e922babdc52f9845dad8
