apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'false'
  name: img4.19.15-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.19.15-x86_64@sha256:d96bf58288bfe00d347707ba0b9fa5455ee0d506ae4dfe417518473197ee16ab
