apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'true'
  name: img4.5.17-x86-64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.5.17-x86_64
