apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: 'true'
  name: img4.16.25-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.16.25-multi
