apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.22.2-multi
    visible: 'true'
  name: img4.22.2-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.22.2-multi
