apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.22.5-multi
    visible: 'true'
  name: img4.22.5-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:a1b3c5e41057af7e04f10110ed73d6013e72b2fdfb385eccf7c7be65f14daded
