---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.9-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.9-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:4ca459a8eebc78d940682aaa5a57f6d72d8559259fba49f1ec25c2ae15931724
