---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.37-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.37-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:5b856e1ffca97c4a5a3c1847b27db3f0b37694d456c41362b4256171f70031dd
