---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.34-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.34-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:d6449290ca99d13698e7aedea51a8637cae7663a3dbc1231c33f5b48154daee0
