---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.25-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.25-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:490002f6d1363683178f4b9999f52602588f3cb75a9267a190fdfdee06e2db7a
