---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.42-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.42-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:96113f9831313f90e1cf9b5f873ae201831d679fc55b60cf4eedecfbbd8434ab
