---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.21-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.21-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:54c81ab130a264829c9a3434df1005074cc9b2edc8e31ead40ac94faf3debf72
