---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.27-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.27-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:05f959160351e81679dfab48bab274579fcc320244cabe974410718b132445b1
