---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.42-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.42-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:d20702b31fc7c2b0954042bd4723414f1f54b121fe9813dd2c06f9325088d0b7
