---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.18-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 4.20.18-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:2dab927fd20984e247301b2483083b71f942a1f550f5d8a1db42897edc042e39
