---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img4.20.13-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.20.13-x86_64@sha256:280ffe256696c1b3699a5d0bc9c520b785a0c6acff0ed58073adbd206185c4b9
