apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.20.36-x86_64
    visible: 'false'
  name: img4.20.36-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:8fcb7da94ab599d7aa92adfcffdcda19cef1f3c2903bc9d38006b7522847c458
