---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img5.0.0-rc.0-x86-64-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 5.0.0-rc.0-x86_64
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:2ab7a19fc44896fe6c860a039c673349ed795d01b3ce82ccbfbdcc1c23177966
