---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img5.0.0-ec.3-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 5.0.0-ec.3-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:006f6da1732807973653ae77b79d3dadd5595c9c9cee5b727751838e8e5fd144
