---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: img5.0.0-ec.5-multi-appsub
  labels:
    channel: candidate
    visible: "false"
    releaseTag: 5.0.0-ec.5-multi
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:d1c0459e0a513c95a3946ae16d9c88b7fc85c5a53960ead6ac56646ec5c593cb
