apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'false'
  name: img4.19.0-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.19.0-multi@sha256:2ad438481986f973b7ed55a59221b7ce559cf1fe13786ed4a7746fdbdff4681c
