apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.21.14-multi
    visible: 'true'
  name: img4.21.14-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:4b92a67215c370b932f9e9dc3b5d0ccd704903049c1127e00b7fc6a52cee258c
