apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.21.0-x86_64
    visible: 'false'
  name: img4.21.0-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:9f42dbb302232b32a7b07cc284eee1c7d1bddf79be4ad88dae0598cbad0bb23e
