apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.21.11-x86_64
    visible: 'false'
  name: img4.21.11-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:a2726e3135049af3b889450a6ffcd81605b9a42dd24e5b3b7bc42621548366c2
