apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.21.5-x86_64
    visible: 'false'
  name: img4.21.5-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:sha256:ae0711cb2b35d8661d086945e0578f9cd2d417093e910e47169447db5dd9f8bd
