apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    releaseTag: 4.21.10-multi
    visible: 'false'
  name: img4.21.10-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:214a9aad5443a9ad6e4450c1ea67e741a42c7dcea9bf0f5f4c4fad0b91378bbe
