apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'false'
  name: img4.19.0-x86-64-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.19.0-x86_64@sha256:3482dbdce3a6fb2239684d217bba6fc87453eff3bdb72f5237be4beb22a2160b
