apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'true'
  name: img4.19.21-multi-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.19.21-multi@sha256:ce9df9d832592e262159af5676cee3636f93c5580f576bcb6544d343601c6095
